scripts/deleteOldArtifacts.fsx: fix JSON provider
Change type of artifacts.id to be int64, because its value may
not be in int32 range and cause an error like this:
```
System.Exception: Expecting an Int32 at '/artifacts[1]/id', got 4823510038
```