CI: run commitlint tests outside of container
Commitlint fails to execute because a Git error is occurring
and it cannot recognize the Git repository:

```
Error: fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

After investigating, I found out that when we run the
commitlint plugins tests job on a Docker container, there’s
no `.git` directory at all.

Also, when `tsc` is executed, `commitlint.config.js` will be
created and commitlint mistakenly reads that file instead
of `commitlint.config.ts`. It is always better to use tsconfig
`outDir` flag to prevent this issues.