CI: no need to install commitlint in TS build
However, we still need to install the types lib, otherwise
we would get this compiler error:

```
commitlint.config.ts(3,36): error TS2307: Cannot find module '@commitlint/types' or its corresponding type declarations.
```