jest.config,CI: convert to typescript
The --config parameter is included due to the fact that tsc
creates a jest.config.js file. If this parameter is not
specified, we encounter an error stating:
"Multiple configurations found".

Also we need to install ts-node:

```
  Error: Jest: 'ts-node' is required for the TypeScript configuration files. Make sure it is installed
```