scripts: add nuget sanity check
This script requires the packages directory, so a NuGet.config
file had to be created to set it, otherwise the following
would occur:

```
Run dotnet fsi scripts/sanitycheck.fsx
8 nuget packages found for solution conventions.sln
System.Exception: 'packages' subdir under solution dir /__w/conventions/conventions/packages doesn't exist, run `make` first
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1439.Invoke(String message) in /build/dotnet6-FDnqMS/dotnet6-6.0.123/src/fsharp/artifacts/source-build/self/src/src/fsharp/FSharp.Core/printf.fs:line 1439
   at FSI_0007.findMissingPackageDirs@244(DirectoryInfo solDir, FSharpMap`2 idealPackageDirs)
   at FSI_0007.sanityCheckNugetPackagesFromSolution@120(FileInfo sol)
   at FSI_0007.SanityCheckNugetPackages()
   at <StartupCode$FSI_0007>.$FSI_0007.main@()
Stopped due to error
Error: Process completed with exit code 1.
```

NOTE: This code comes originally from geewallet at the time
of writing [1] (and so it will be removed from there soon),
but we have discarded the parts of it that deal with legacy
.NET4.x (such as packages.config files).

[1] https://github.com/nblockchain/geewallet/blob/master/scripts/sanitycheck.fsx

Co-authored-by: Andres G. Aragoneses <knocte@gmail.com>