GithubCI: pin commitlint version
To 20.3.1 because latest version (20.4.0) breaks the build:
```
commitlint/helpers.ts(14,32): error TS2693: 'URL' only refers to a type, but is being used as a value here.
commitlint/plugins.ts(98,44): error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
commitlint/tests/plugins.test.ts(605,22): error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.
commitlint/tests/plugins.test.ts(720,5): error TS2584: Cannot find name 'console'. Do you need to change your target library? Try changing the 'lib' compiler option to include 'dom'.
commitlint/tests/testHelpers.ts(3,27): error TS2307: Cannot find module 'child_process' or its corresponding type declarations.
commitlint/tests/testHelpers.ts(4,16): error TS2307: Cannot find module 'os' or its corresponding type declarations.
```