CI,commitlint/tests: migrate from jest to vitest
Migrate to vitest test framework as jest doesn't have
support for ES modules.

Set `skipLibCheck` in tsconfig.json to true because otherwise
compiling test files produces errors like this:
```
node_modules/vite-node/dist/index-WT31LSgS.d.ts:83:14 - error TS2304:
Cannot find name 'WebSocket'.
```