GitHubCI: improve nodejs update mechanism
We found this easier method in StackOverflow [1].
The regression we were getting in the SanityCheck
job was:

```
+ npx commitlint --version
@commitlint/cli@17.6.5
+ npx commitlint --from HEAD~1 --to HEAD --verbose
/__w/conventions/conventions/node_modules/typescript/lib/typescript.js:139
    for (let i = startIndex ?? 0; i < array.length; i++) {
                             ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at attemptRequireWithV8CompileCache (/__w/conventions/conventions/node_modules/ts-node/dist/util.js:104:16)
    at loadCompiler (/__w/conventions/conventions/node_modules/ts-node/dist/configuration.js:237:56)
    at resolveAndLoadCompiler (/__w/conventions/conventions/node_modules/ts-node/dist/configuration.js:226:16)
```

[1] https://stackoverflow.com/a/74217960/544947